const PRICE_CHECKING_INTERVAL = 20000;
const SYNCHING_INTERVAL = 120000;
const MAX_UNDO_REMOVED_ITEMS = 10;
const UNDO_REMOVED_ITEMS_TIMEOUT = 120000;
const DEFAULT_TITLE = "Price Tag";
const TRACKED_ITEM_TITLE = "Price Tag - This item is being tracked";
const EXTENSION_MESSAGES = {
    POPUP_STATUS: "POPUP.STATUS",
    RECORD_ATTEMPT: "RECORD.ATTEMPT",
    RECORD_START: "RECORD.START",
    RECORD_CANCEL: "RECORD.CANCEL",
    AUTO_SAVE_STATUS: "AUTO_SAVE.STATUS",
    AUTO_SAVE_CHECK_STATUS: "AUTO_SAVE.CHECK_STATUS",
    AUTO_SAVE_ATTEMPT: "AUTO_SAVE.ATTEMPT",
    AUTO_SAVE_HIGHLIGHT_PRE_START: "AUTO_SAVE.HIGHLIGHT.PRE_START",
    AUTO_SAVE_HIGHLIGHT_PRE_STOP: "AUTO_SAVE.HIGHLIGHT.PRE_STOP",
    PRICE_TAG_HIGHLIGHT_START: "PRICE_TAG.HIGHLIGHT.START",
    PRICE_TAG_HIGHLIGHT_STOP: "PRICE_TAG.HIGHLIGHT.STOP",
    CONFIRMATION_DISPLAY_CREATE: "CONFIRMATION_DISPLAY.CREATE",
    CONFIRMATION_DISPLAY_LOAD: "CONFIRMATION_DISPLAY.LOAD",
    CONFIRMATION_DISPLAY_REMOVE: "CONFIRMATION_DISPLAY.REMOVE"
};

export {
    DEFAULT_TITLE,
    TRACKED_ITEM_TITLE,
    PRICE_CHECKING_INTERVAL,
    SYNCHING_INTERVAL,
    MAX_UNDO_REMOVED_ITEMS,
    UNDO_REMOVED_ITEMS_TIMEOUT,
    EXTENSION_MESSAGES
};
