const PRICE_CHECKING_INTERVAL = 180000;
const SYNCHING_INTERVAL = 120000;
const MAX_UNDO_REMOVED_ITEMS = 10;
const UNDO_REMOVED_ITEMS_TIMEOUT = 120000;

export {
    PRICE_CHECKING_INTERVAL,
    SYNCHING_INTERVAL,
    MAX_UNDO_REMOVED_ITEMS,
    UNDO_REMOVED_ITEMS_TIMEOUT
};
