const PRICE_CHECKING_INTERVAL = 20000;
const SYNCHING_INTERVAL = 120000;
const MAX_UNDO_REMOVED_ITEMS = 10;
const UNDO_REMOVED_ITEMS_TIMEOUT = 120000;
const DEFAULT_TITLE = "Price Tag";
const TRACKED_ITEM_TITLE = "Price Tag - This item is being tracked";

export {
    DEFAULT_TITLE,
    TRACKED_ITEM_TITLE,
    PRICE_CHECKING_INTERVAL,
    SYNCHING_INTERVAL,
    MAX_UNDO_REMOVED_ITEMS,
    UNDO_REMOVED_ITEMS_TIMEOUT
};
